language: node_js

services:
  - docker

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

script:
  - yarn build
  - yarn test

after_success:
  - if [ $TRAVIS_PULL_REQUEST == “false” ] && [ $TRAVIS_BRANCH == “master” ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dina-collections-ui .;
    docker tag dina-collections-ui dina/dina-collections-ui;
    docker push dina/dina-collections-ui;
    fi
